-- DDL Data Definition Language
DROP TABLE IF EXISTS military_ranks;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS equipment_types;
DROP TABLE IF EXISTS parameter_types;
DROP TABLE IF EXISTS units;
DROP TABLE IF EXISTS measurements;
DROP TABLE IF EXISTS measurements_bucket;
DROP TABLE IF EXISTS unit_conversions;

-- Звания
CREATE TABLE IF NOT EXISTS military_ranks (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT UNIQUE NOT NULL
); 

-- Работники
CREATE TABLE IF NOT EXISTS employees (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    surname TEXT NOT NULL,
    rank_id INT
);

-- Типы оборудования для измерений
CREATE TABLE IF NOT EXISTS equipment_types (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL UNIQUE,
    abbreviation TEXT NOT NULL UNIQUE
);

-- Типы параметров, возможные параметры без единиц измерения
CREATE TABLE IF NOT EXISTS parameter_types (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT UNIQUE NOT NULL,
);

-- Единицы измерения
CREATE TABLE IF NOT EXISTS units (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT UNIQUE NOT NULL,
    abbreviation TEXT NOT NULL UNIQUE
);

-- Параметры с единицами измерения, не хранит измерения
CREATE TABLE IF NOT EXISTS parameters (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parameter_type_id INT NOT NULL,
    unit_id INT NOT NULL
    -- Можно сделать primary key комбинацию из айди параметров и айди единиц измерения
);

-- Измерения
CREATE TABLE IF NOT EXISTS measurements (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    measurements_bucket INT NOT NULL,
    equipment_type_id INT NOT NULL, -- Можно перенести в параметры, чтобы уточнять в них оборудование, которое нужно для измерения
    parameter_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(), -- Возможно, стоит перенести в пачки измерений, потому что в приложении не подразумеваются отдельные измерения
    value DECIMAL(10) NOT NULL
);

-- Пачки измерений
CREATE TABLE IF NOT EXISTS measurements_buckets (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INT NOT NULL
);

-- Таблица для перевода единиц измерения
CREATE TABLE IF NOT EXISTS unit_conversions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- parameter_type_id INT NOT NULL, -- Можно добавить для проверки типа параметра
    from_unit_id INT NOT NULL,
    to_unit_id INT NOT NULL,
    value DECIMAL(10)
    -- Можно сделать primary key комбинацию из айди начальных и конечных единиц измерения
);