-- Скрипт для миграции с прошлой версии базы данных

-- Осталось прежним:
-- equipment_types

-- Переименовал:
-- ranks -> military_ranks
-- users -> employees

-- Новые таблицы:
-- parameter_types - типы измерений, то есть возможные параметры для измерений
-- units - единицы измерения
-- measurements_bucket - соединяет измерения в пачки
-- unit_conversions - таблица для перевода одной единицы измерения в другую

-- Обновил структуру:
-- parameters - теперь хранит единичный параметр, а не измерения всех параметров
-- measurements - теперь хранит единичное измерение, а не ссылку на измерения всех параметров

BEGIN;

-- Простые переименования
ALTER TABLE ranks RENAME TO military_ranks;
ALTER TABLE users RENAME TO employees;

-- Изменение типов колонок на VARCHAR
ALTER TABLE military_ranks ALTER COLUMN title TYPE VARCHAR(100);
ALTER TABLE employees ALTER COLUMN "name" TYPE VARCHAR(100);
ALTER TABLE employees ALTER COLUMN surname TYPE VARCHAR(100);
ALTER TABLE equipment_types ALTER COLUMN title TYPE VARCHAR(100);
ALTER TABLE equipment_types ALTER COLUMN abbreviation TYPE VARCHAR(20);

-- Создание новых таблиц
-- Типы параметров, возможные параметры без единиц измерения
CREATE TABLE parameter_types (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) UNIQUE NOT NULL
); 
-- Единицы измерения
CREATE TABLE units (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) UNIQUE NOT NULL,
    abbreviation VARCHAR(20) NOT NULL UNIQUE
);
-- Пачки измерений
CREATE TABLE measurements_buckets (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INT NOT NULL
);
-- Таблица для перевода единиц измерения
CREATE TABLE unit_conversions (
    from_unit_id INT NOT NULL,
    to_unit_id INT NOT NULL,
    from_value DECIMAL(10, 0),
    to_value DECIMAL(10, 0),
    PRIMARY KEY (from_unit_id, to_unit_id)
);

-- Создание временных таблиц для переноса данных
-- Параметры с единицами измерения, не хранит измерения. То есть связка параметров и единиц измерения
CREATE TABLE temp_parameters (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parameter_type_id INT NOT NULL,
    unit_id INT NOT NULL,
    default_value DECIMAL(10, 0) NULL,
    min_value DECIMAL(10, 0) NULL,
    max_value DECIMAL(10, 0) NULL
);
-- Измерения
CREATE TABLE temp_measurements (
    measurements_bucket_id INT NOT NULL,
    equipment_type_id INT NOT NULL, -- Можно перенести в параметры, чтобы уточнять в них оборудование, которое нужно для измерения
    parameter_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Возможно, стоит перенести в пачки измерений, потому что в приложении не подразумеваются отдельные измерения
    "value" DECIMAL(10, 0) NOT NULL,
    PRIMARY KEY (measurements_bucket_id, parameter_id) -- Гарантирует, что в пачке только одно измерение одного параметра
);

-- Перенос данных из старых таблиц
-- Типы параметров из прошлых таблиц
INSERT INTO parameter_types (title) 
VALUES ('Высота метеопоста'),
    ('Температура'),
    ('Давление'),
    ('Направление ветра'),
    ('Скорость ветра'),
    ('Дальность сноса пуль')
ON CONFLICT DO NOTHING;
-- Единицы измерения из прошлых таблиц
INSERT INTO units (title, abbreviation) 
VALUES ('Метр', 'м'), -- Используется для высоты и для дальности
    ('1/10 градуса по Цельсию', '*C/10'),
    ('Миллиметр ртутного столба', 'мм рт. ст.'),
    ('Деление угломера', 'дел. угл.'),
    ('Метр в секунду', 'м/с'),
    ('Градус по Цельсию', '*C')
ON CONFLICT DO NOTHING;
-- Параметры из прошлых таблиц
INSERT INTO temp_parameters (id, parameter_type_id, unit_id, default_value, min_value, max_value)
VALUES (1, 1, 1, 100, NULL, NULL),
    (2, 2, 2, 150, -580, 580), -- десятые градуса
    (3, 3, 3, 750, 500, 900),
    (4, 4, 4, 0, 0, 59),
    (5, 5, 5, 0, 0, 15),
    (6, 6, 1, 0, 0, 150) -- Тоже метры
ON CONFLICT DO NOTHING;
-- Таблица для переводов единиц измерения
INSERT INTO unit_conversions (from_unit_id, to_unit_id, from_value, to_value) 
VALUES (2, 6, 10, 1) -- перевод в целые градусы
-- из 10 (1/10 градусов) в 1 (целых градусов)
ON CONFLICT DO NOTHING;

-- Переносим данные измерений в новую схему
-- Заполняем таблицу с единичными измерениями
INSERT INTO temp_measurements
(measurements_bucket_id, equipment_type_id, parameter_id, created_at, "value")
-- Высота
SELECT m.id, p.equipment_type_id, 1, m.created_at, p.station_height
FROM measurements m
JOIN parameters p ON p.id = m.parameters_id
UNION ALL
-- Температура
-- Умножаем градусы на 10, чтобы получить 1/10 градусов, и переводим в DECIMAL(10)
SELECT m.id, p.equipment_type_id, 2, m.created_at, CAST(p.temperature * 10 AS DECIMAL(10, 0))
FROM measurements m
JOIN parameters p ON p.id = m.parameters_id
UNION ALL
-- Давление
SELECT m.id, p.equipment_type_id, 3, m.created_at, p.pressure
FROM measurements m
JOIN parameters p ON p.id = m.parameters_id
UNION ALL
-- Направление ветра
SELECT m.id, p.equipment_type_id, 4, m.created_at, p.wind_direction
FROM measurements m
JOIN parameters p ON p.id = m.parameters_id
UNION ALL
-- Скорость ветра
SELECT m.id, p.equipment_type_id, 5, m.created_at, p.wind_speed
FROM measurements m
JOIN parameters p ON p.id = m.parameters_id
WHERE p.wind_speed IS NOT NULL -- чтобы не было пустых
UNION ALL
-- Дальность снова пуль
SELECT m.id, p.equipment_type_id, 6, m.created_at, p.bullet_drift_distance
FROM measurements m
JOIN parameters p ON p.id = m.parameters_id
WHERE p.bullet_drift_distance IS NOT NULL; -- чтобы не было пустых

-- Измерения из прошлой схемы становятся как бы пачкой (бакетом) измерений из новой
INSERT INTO measurements_buckets (id, employee_id)
SELECT id, user_id
FROM measurements;

-- Удаление старых таблиц
DROP TABLE measurements CASCADE;
DROP TABLE parameters CASCADE;

-- Переименование временных таблиц в постоянные
ALTER TABLE temp_parameters RENAME TO parameters;
ALTER TABLE temp_measurements RENAME TO measurements;

COMMIT;