-- DDL Data Definition Language

CREATE TABLE IF NOT EXISTS "users" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "surname" TEXT NOT NULL,
    "rank_id" INT
);

CREATE TABLE IF NOT EXISTS "ranks" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "equipment_types" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" TEXT NOT NULL UNIQUE,
    "abbreviation" TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "parameters" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "equipment_type_id" INT NOT NULL,
    "station_height" INT DEFAULT 100 NOT NULL,
    "temperature" DECIMAL(3, 1) DEFAULT 15 NOT NULL CHECK (
        -58 <= "temperature"
        AND "temperature" <= 58
    ),
    "pressure" SMALLINT DEFAULT 750 NOT NULL CHECK (
        500 <= "pressure"
        AND "pressure" <= 900
    ),
    "wind_direction" SMALLINT DEFAULT 0 NOT NULL CHECK (
        0 <= "wind_direction"
        AND "wind_direction" <= 59
    ),
    "wind_speed" SMALLINT DEFAULT NULL NULL CHECK (
        0 <= "wind_speed"
        AND "wind_speed" <= 15
    ),
    "bullet_drift_distance" SMALLINT DEFAULT NULL NULL CHECK (
        0 <= "bullet_drift_distance"
        AND "bullet_drift_distance" <= 150
    )
);

CREATE TABLE IF NOT EXISTS "measurements" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INT NOT NULL,
    "parameters_id" INT NOT NULL,
    "created_at" TIMESTAMP DEFAULT NOW()
);